name: Deploy Worker
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Modify /src/api.ts before deployment
        run: |
          sed '/const body = await c.req.json<OpenAI.ChatCompletionCreateParams>();/a\ \ if (body.frequency_penalty === 1 \&\& body.presence_penalty === 1) {\n    body.frequency_penalty = 0;\n  }' src/api.ts > src/temp_api.ts && mv src/temp_api.ts src/api.ts

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --minify src/index.ts
